### ISSUE TITLE
Fix corrupted data on dwm1000 distance devices

### ISSUE THREAD

**Issue by JoshuaBThompson** [JoshuaBThompson/WristBand#16]
Integrated the chips with the new pcb boards and tested with some test code from github.
Connectivity over spi communication bus test worked. But, when configuring one device as a sender and the other device as a receiver, the receiver would only receive corrupted data and at a very slow pace (about once every 1 - 3 minutes) or sometimes not receive any data at all. 
Looking at the code the error is caught when a device clock anomaly is detected. According to some comments from another user on github they are experiencing a similar issue. The maintainer of the github codebase responded to the issue by saying it might be a hardware configuration problem. So, in other words I might of fried one of the boards when soldering or accidentally reversing polarity of the power lines (which I think I might have done once ...)

Things to do to resolve:
- [x] Purchase 2 new dwm1000 modules
- [x] Purchase 2 new pcb interface boards
- [ ] resolder but be extra careful.
- [ ] add a diode between the power lines of the dwm1000 to prevent damage if accidentally reverse pwr polarity
- [ ] while waiting for new components (above) test the setup with a 1000 ohm resistor instead of a 220 ohm
- [ ] test more of the spi communication by reading as much configuration data from each device to see if there are any registers configured incorrectly
- [ ] check the configuration of the irq pin via spi
- [ ] check to see if receiver dwm1000 is in idle state when receive code running (should not be)

**Comment by JoshuaBThompson** [comment]
purchased new equipment. Should be here in 7 days.

**Comment by JoshuaBThompson** [comment]
closing since delaying this feature for a while
